# Generated by Django 5.2.6 on 2025-09-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["topic", "title"], name="lessons_topic_i_86c8f9_idx"
            ),
        ),
    ]
