# Generated by Django 5.2.6 on 2025-09-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_content_lesson_lessons_topic_i_86c8f9_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_hls',
            field=models.FileField(blank=True, null=True, upload_to='videos/hls/'),
        ),
    ]
