# Generated by Django 5.2.6 on 2025-09-30 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_video_hls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_hls',
        ),
    ]
