# Generated by Django 5.2.6 on 2025-09-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_lesson_video_hls'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='hls_playlist',
            field=models.CharField(blank=True, help_text='Converted HLS playlist (.m3u8) file path', max_length=500, null=True),
        ),
    ]
