# Generated by Django 5.2.6 on 2025-09-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_hls_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='hls_playlist',
        ),
    ]
